### PR TITLE
Allow using Symfony 6 & drop not maintained PHP & Symfony releases

### PR DESCRIPTION
**Pull request by stloyd**

### CODE REVIEW

**Comment by stloyd** [comment]
@lchrusciel This is required to allow Symfony 6 on Grid bundle.

**Comment by loic425** [comment]
@stloyd Could you drop support for php7.4?

Cause @lchrusciel said: "we are about to bump all deps of Sylius to PHP ^8.0, and SF ^4.4 || ^5.4"

**Comment by Zales0123** [comment]
👍 for dropping `^7.4`, it's not fully supported anymore, there is no point in staying with it. Let's _be the change we want to see in the open-source world_ 😄 🚀

**Comment by stloyd** [comment]
Closed in favor of #2.

**Pull request closed without merging**
